language: php

php:
  - 7.2

addons:
  code_climate:
    repo_token: 2a7b11d0f28b7859b139111f4fc6bcd141d1b1fdfec5e08cade71225f4680608

before_script:
  - composer install

script:
  - phpunit --configuration phpunit.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
  - ./vendor/bin/test-reporter